services:
  postgres:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: taskiq_user
      POSTGRES_PASSWORD: "gOxN5hbl7geTwgvS"
      POSTGRES_DB: taskiq
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "taskiq_user", "-d", "taskiq"]
      interval: 3s
      timeout: 1s
      retries: 5
    networks:
      - default

  oracle:
    image: gvenzl/oracle-xe:21-slim
    restart: always
    environment:
      ORACLE_DATABASE: taskiq
      ORACLE_PASSWORD: "gOxN5hbl7geTwgvS"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./initdb.d/01-oracle-grants.sql:/container-entrypoint-initdb.d/01-oracle-grants.sql:ro
    ports:
      - 1521:1521
      - 5500:5500
    healthcheck:
      test: ["CMD-SHELL", "healthcheck.sh"]
      interval: 3s
      timeout: 1s
      retries: 5
    networks:
      - default

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      SA_PASSWORD: "gOxN5hbl7geTwgvS"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./initdb.d/01-mssql-init.sql:/docker-entrypoint-initdb.d/01-mssql-init.sql:ro
    ports:
      - 1433:1433
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P gOxN5hbl7geTwgvS -C -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
    networks:
      - default
  mssql.configurator:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - ./initdb.d/01-mssql-init.sql:/docker-entrypoint-initdb.d/01-mssql-init.sql:ro
    depends_on:
      mssql:
        condition: service_healthy
    command: >
      bash -c '
      /opt/mssql-tools18/bin/sqlcmd -S mssql -U sa -P gOxN5hbl7geTwgvS -C -i docker-entrypoint-initdb.d/01-mssql-init.sql;
      echo "All done!";
      '
    networks:
      - default

volumes:
  postgres_data:
  oracle_data:
  mssql_data:
networks:
  default:
    driver: bridge
